# Generated by Django 2.1.5 on 2019-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190109_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
